update for quarkus 3.0.0 (javax/jakarta)
quarkiverse/quarkus-logging-json pull request #227
Opened 2023-04-02 09:37 UTC by KarlScheibelhofer

Because I needed a local build that works with Quarkus 3.0.0.CR1 even for native image builds, I did a fork and quick fix of he quarkiverse/quarkus-logging-json extension. I needed the io.quarkiverse.loggingjson.providers.KeyValueStructuredArgument.kv. 
Please note the disabled jacoco in the pom.xml because I struggled getting it working here.
Maybe you can consider to integrate these changes.

2023-04-15 18:05 UTC, kjq commented
We would be willing to commit resources to maintain this extension if that is an option.  Another alternative is we can submit a fork of this as a new logging extension. As of right now, our upgrade is at a stand-still without this and we are also using an internal dependency.

2023-04-16 10:55 UTC, SlyngDK requested changes
@KarlScheibelhofer I have tested local and it is working fine with jacoco.

2023-04-16 10:55 UTC, SlyngDK commented on pom.xml
> +<!--
I have tested local and is working, please uncomment.

2023-04-16 10:55 UTC, SlyngDK commented on pom.xml
> +<!--
I have tested local and is working, please uncomment.

2023-04-16 10:55 UTC, SlyngDK commented on pom.xml
> +<!--
I have tested local and is working, please uncomment.

2023-04-18 17:07 UTC, gastaldi commented
- Superseded by https://github.com/quarkiverse/quarkus-logging-json/pull/234

2023-04-18 17:07 UTC, closed without merging